# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

parameters:
    - name: FolderPath
      type: string
      default: $(System.DefaultWorkingDirectory)
    - name: Pattern
      type: string
      default: ".*.dll"

steps:
    - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@5
      displayName: ESRP DLL CodeSigning
      inputs:
        ConnectedServiceName: 'esrpsigning-ztassessment-wif' 
        AppRegistrationClientId: '$(EsrpAppRegistrationClientId)'
        AppRegistrationTenantId: '$(EsrpAppRegistrationTenantId)'
        AuthAKVName: $(EsrpAuthAKVName)
        AuthCertName: $(EsrpAuthCertName)
        AuthSignCertName: $(EsrpAuthSignCertName)
        ServiceEndpointUrl: '$(EsrpServiceEndpointUrl)'
        FolderPath: ${{ parameters.FolderPath }}
        Pattern: ${{ parameters.Pattern }}
        SessionTimeout: 160
        MaxConcurrency: 25
        signConfigType: inlineSignParams
        inlineOperation: |
            [
                {
                    "keyCode": "CP-230012",
                    "operationSetCode": "SigntoolSign",
                    "parameters": [
                        {
                            "parameterName": "OpusName",
                            "parameterValue": "Microsoft"
                        },
                        {
                            "parameterName": "OpusInfo",
                            "parameterValue": "http://www.microsoft.com"
                        },
                        {
                            "parameterName": "FileDigest",
                            "parameterValue": "/fd \"SHA256\""
                        },
                        {
                            "parameterName": "PageHash",
                            "parameterValue": "/NPH"
                        },
                        {
                            "parameterName": "TimeStamp",
                            "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                        }
                    ],
                    "toolName": "sign",
                    "toolVersion": "1.0"
                },
                {
                    "keyCode": "CP-230012",
                    "operationSetCode": "SigntoolVerify",
                    "parameters": [],
                    "toolName": "sign",
                    "toolVersion": "1.0"
                }
            ]
