on: [pull_request]

jobs:
  validate:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Prerequisites
      run: .\build\powershell\Install-Prerequisites.ps1
      shell: pwsh
    - name: Validate
      run: .\code-tests\pester.ps1
      shell: pwsh
