name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'src/react/**'
  workflow_dispatch:

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: src/react/package-lock.json
      - name: Install dependencies
        working-directory: ./src/react
        run: npm ci
      - name: Build website
        working-directory: ./src/react
        run: npm run build
      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./src/react/build

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
